name: PayID PR Coverage Action

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
#    types: [opened, closed]
    branches:
      - master


jobs:
  pay:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Run PayID
      uses: hammertoe/payid_xrp_pr_coverage_action@test_branch
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        wallet_secret: ${{ secrets.PAYID_WALLET_SECRET }}
        amount: 1000000

        